apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ .Chart.Name }}-post-install-hook-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app:  {{ .Chart.Name }}-post-install-hook-{{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        env:
          - name: TZ
            value: Asia/Seoul
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
      restartPolicy: Never
  backoffLimit: 1
